var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/notifications/read-all/route.js")
R.c("server/chunks/_04601f3f._.js")
R.c("server/chunks/_aa6e99b0._.js")
R.c("server/chunks/[root-of-the-server]__44baabec._.js")
R.c("server/chunks/_b26786c3._.js")
R.c("server/chunks/[root-of-the-server]__f408c708._.js")
R.c("server/chunks/src_lib_user-accounts_7a5c54d8.js")
R.c("server/chunks/_next-internal_server_app_api_notifications_read-all_route_actions_b776892e.js")
R.m(43462)
module.exports=R.m(43462).exports
