var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/hris/incidents/route.js")
R.c("server/chunks/src_lib_852092e8._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_e02e290d.js")
R.c("server/chunks/[root-of-the-server]__3476a93a._.js")
R.c("server/chunks/_aa6e99b0._.js")
R.c("server/chunks/_50ac50e3._.js")
R.c("server/chunks/[root-of-the-server]__f408c708._.js")
R.c("server/chunks/src_lib_security-detection_4bdbe3ad.js")
R.c("server/chunks/src_lib_hris-backend_4dbd0cdd.js")
R.c("server/chunks/_next-internal_server_app_api_hris_incidents_route_actions_e0ab9189.js")
R.m(69467)
module.exports=R.m(69467).exports
