var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/retention/purge/route.js")
R.c("server/chunks/[root-of-the-server]__bc1cae1e._.js")
R.c("server/chunks/src_lib_hris-backend_4dbd0cdd.js")
R.c("server/chunks/_aa6e99b0._.js")
R.c("server/chunks/src_lib_user-accounts_7a5c54d8.js")
R.c("server/chunks/_b26786c3._.js")
R.c("server/chunks/[root-of-the-server]__f408c708._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_retention_purge_route_actions_525cbe9d.js")
R.m(72802)
module.exports=R.m(72802).exports
