var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/hris/lifecycle/[recordId]/approve/route.js")
R.c("server/chunks/_3910f340._.js")
R.c("server/chunks/_aa6e99b0._.js")
R.c("server/chunks/[root-of-the-server]__44baabec._.js")
R.c("server/chunks/_b26786c3._.js")
R.c("server/chunks/[root-of-the-server]__f408c708._.js")
R.c("server/chunks/src_lib_user-accounts_7a5c54d8.js")
R.c("server/chunks/ce889_server_app_api_hris_lifecycle_[recordId]_approve_route_actions_07bfeb6b.js")
R.m(82690)
module.exports=R.m(82690).exports
