var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/hris/settings/reference-data/route.js")
R.c("server/chunks/_f3229a5d._.js")
R.c("server/chunks/src_lib_hris-backend_4dbd0cdd.js")
R.c("server/chunks/[root-of-the-server]__3476a93a._.js")
R.c("server/chunks/_b26786c3._.js")
R.c("server/chunks/[root-of-the-server]__f408c708._.js")
R.c("server/chunks/src_lib_user-accounts_7a5c54d8.js")
R.c("server/chunks/_aa6e99b0._.js")
R.c("server/chunks/ce889_server_app_api_hris_settings_reference-data_route_actions_727299b0.js")
R.m(43838)
module.exports=R.m(43838).exports
