// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = never
type AppRouteHandlerRoutes = "/api/admin/retention/purge" | "/api/admin/users" | "/api/admin/users/[userId]/role" | "/api/admin/users/[userId]/status" | "/api/audit/page-view" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/profile" | "/api/auth/profile/activity" | "/api/auth/role" | "/api/auth/sessions/revoke" | "/api/hris/activity-logs" | "/api/hris/attendance" | "/api/hris/attendance/[recordId]" | "/api/hris/attendance/leave-requests" | "/api/hris/attendance/leave-requests/[recordId]" | "/api/hris/employees" | "/api/hris/employees/[recordId]" | "/api/hris/employees/[recordId]/documents/access" | "/api/hris/exports" | "/api/hris/exports/[recordId]" | "/api/hris/exports/[recordId]/approve" | "/api/hris/exports/[recordId]/execute" | "/api/hris/incidents" | "/api/hris/incidents/[recordId]" | "/api/hris/lifecycle" | "/api/hris/lifecycle/[recordId]" | "/api/hris/lifecycle/[recordId]/approve" | "/api/hris/lifecycle/[recordId]/offboard" | "/api/hris/performance" | "/api/hris/performance/[recordId]" | "/api/hris/retention" | "/api/hris/settings/reference-data" | "/api/hris/templates" | "/api/hris/templates/[recordId]" | "/api/invite/verify" | "/api/notifications" | "/api/notifications/[recordId]" | "/api/notifications/read-all"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/admin/retention/purge": {}
  "/api/admin/users": {}
  "/api/admin/users/[userId]/role": { "userId": string; }
  "/api/admin/users/[userId]/status": { "userId": string; }
  "/api/audit/page-view": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/profile": {}
  "/api/auth/profile/activity": {}
  "/api/auth/role": {}
  "/api/auth/sessions/revoke": {}
  "/api/hris/activity-logs": {}
  "/api/hris/attendance": {}
  "/api/hris/attendance/[recordId]": { "recordId": string; }
  "/api/hris/attendance/leave-requests": {}
  "/api/hris/attendance/leave-requests/[recordId]": { "recordId": string; }
  "/api/hris/employees": {}
  "/api/hris/employees/[recordId]": { "recordId": string; }
  "/api/hris/employees/[recordId]/documents/access": { "recordId": string; }
  "/api/hris/exports": {}
  "/api/hris/exports/[recordId]": { "recordId": string; }
  "/api/hris/exports/[recordId]/approve": { "recordId": string; }
  "/api/hris/exports/[recordId]/execute": { "recordId": string; }
  "/api/hris/incidents": {}
  "/api/hris/incidents/[recordId]": { "recordId": string; }
  "/api/hris/lifecycle": {}
  "/api/hris/lifecycle/[recordId]": { "recordId": string; }
  "/api/hris/lifecycle/[recordId]/approve": { "recordId": string; }
  "/api/hris/lifecycle/[recordId]/offboard": { "recordId": string; }
  "/api/hris/performance": {}
  "/api/hris/performance/[recordId]": { "recordId": string; }
  "/api/hris/retention": {}
  "/api/hris/settings/reference-data": {}
  "/api/hris/templates": {}
  "/api/hris/templates/[recordId]": { "recordId": string; }
  "/api/invite/verify": {}
  "/api/notifications": {}
  "/api/notifications/[recordId]": { "recordId": string; }
  "/api/notifications/read-all": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
