var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/hris/attendance/leave-requests/route.js")
R.c("server/chunks/_763e5294._.js")
R.c("server/chunks/_aa6e99b0._.js")
R.c("server/chunks/[root-of-the-server]__3476a93a._.js")
R.c("server/chunks/_50ac50e3._.js")
R.c("server/chunks/[root-of-the-server]__f408c708._.js")
R.c("server/chunks/src_lib_hris-backend_4dbd0cdd.js")
R.c("server/chunks/ce889_server_app_api_hris_attendance_leave-requests_route_actions_df40b210.js")
R.m(69861)
module.exports=R.m(69861).exports
