var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/hris/activity-logs/route.js")
R.c("server/chunks/_0e0f3070._.js")
R.c("server/chunks/_aa6e99b0._.js")
R.c("server/chunks/[root-of-the-server]__26320e6f._.js")
R.c("server/chunks/[root-of-the-server]__f408c708._.js")
R.c("server/chunks/src_lib_user-accounts_7a5c54d8.js")
R.c("server/chunks/_b26786c3._.js")
R.c("server/chunks/_next-internal_server_app_api_hris_activity-logs_route_actions_aaa9ad22.js")
R.m(21669)
module.exports=R.m(21669).exports
