var R=require("../../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/hris/employees/[recordId]/documents/access/route.js")
R.c("server/chunks/_714739ae._.js")
R.c("server/chunks/src_lib_hris-backend_4dbd0cdd.js")
R.c("server/chunks/[root-of-the-server]__3476a93a._.js")
R.c("server/chunks/_b26786c3._.js")
R.c("server/chunks/[root-of-the-server]__f408c708._.js")
R.c("server/chunks/src_lib_user-accounts_7a5c54d8.js")
R.c("server/chunks/_aa6e99b0._.js")
R.c("server/chunks/bec2d_app_api_hris_employees_[recordId]_documents_access_route_actions_b3d700e3.js")
R.m(87470)
module.exports=R.m(87470).exports
