var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/hris/performance/[recordId]/route.js")
R.c("server/chunks/_a8926824._.js")
R.c("server/chunks/_aa6e99b0._.js")
R.c("server/chunks/[root-of-the-server]__3476a93a._.js")
R.c("server/chunks/_50ac50e3._.js")
R.c("server/chunks/src_lib_hris-backend_4dbd0cdd.js")
R.c("server/chunks/[root-of-the-server]__f408c708._.js")
R.c("server/chunks/_next-internal_server_app_api_hris_performance_[recordId]_route_actions_ca500ba9.js")
R.m(90451)
module.exports=R.m(90451).exports
