var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/hris/exports/[recordId]/route.js")
R.c("server/chunks/_c08d0982._.js")
R.c("server/chunks/_aa6e99b0._.js")
R.c("server/chunks/[root-of-the-server]__3476a93a._.js")
R.c("server/chunks/_50ac50e3._.js")
R.c("server/chunks/src_lib_hris-backend_4dbd0cdd.js")
R.c("server/chunks/[root-of-the-server]__f408c708._.js")
R.c("server/chunks/_next-internal_server_app_api_hris_exports_[recordId]_route_actions_9a5475b3.js")
R.m(74740)
module.exports=R.m(74740).exports
